export type ScreenParamsType = {
  Home: undefined;
  Profile: undefined;
  Settings: undefined;
  Details: { id: string };
  Messages: { id: string };
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  ResetPassword: undefined;
  ChangePassword: undefined;
  About: undefined;
  Terms: undefined;
  Privacy: undefined;
  Contact: undefined;
  FAQ: undefined;
  Support: undefined;
  Feedback: undefined;
  Notifications: undefined;
  Cart: undefined;
  Checkout: undefined;
  Shops: undefined;
  Stacks: { screen: string, params: { id: string } };
  Order: undefined;
  Tabs: { screen: string, params?: { screen?: string, params?: { id: string } } };
  Verify: { from: string, email: string };
  Reset: undefined;
};
